### PR TITLE
Fixed A Command In The Documentation

### PR DESCRIPTION
**Pull request by oscartbeaumont**
The "kr add" command requires having "--server" before the servers address.

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
If this PR is even still relevant why has it not gone through. Do I need to do something?

**Comment by FinHorsley** [comment]
Can this please be merged, as I ran into the same error when using `kr add <user>@<server>` instead of `kr add --server <user>@<server>`

**Comment by oscartbeaumont** [comment]
Is there a reason this hasn't been merged. I haven't checked if it is still relevant but I would like to get the changes merged or the issue closed if that is possible.

**Comment by oscartbeaumont** [comment]
I am closing this as the maintainers have not merged it.

**Pull request closed without merging**
